# Local development services for debugging
# Run with: docker-compose -f docker-compose.local.yml up -d

version: '3.8'

services:
  # Local DynamoDB for development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-optimizeDbBeforeStartup"]
    networks:
      - local-dev

  # DynamoDB Admin UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    networks:
      - local-dev

  # LocalStack for additional AWS services (optional)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,lambda,apigateway,cloudwatch,logs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./local-data:/var/lib/localstack"
    networks:
      - local-dev

networks:
  local-dev:
    driver: bridge

volumes:
  dynamodb-data: