spring:
  application:
    name: product-service
  main:
    web-application-type: none
  cloud:
    function:
      definition: productHandler

# AWS Lambda Configuration
aws:
  lambda:
    function-name: ${LAMBDA_FUNCTION_NAME:product-service}
    
# Logging configuration
logging:
  level:
    software.amazonaws.example: INFO
    org.springframework.cloud.function: INFO
    
# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  level:
    software.amazonaws.example: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.boot.devtools: DEBUG

---
spring:
  config:
    activate:
      on-profile: native
  aot:
    enabled: true
    
# Disable Actuator for native builds to avoid compatibility issues
management:
  endpoints:
    enabled-by-default: false
    
logging:
  level:
    software.amazonaws.example: INFO
    
---
spring:
  config:
    activate:
      on-profile: prod
  aot:
    enabled: true
    
logging:
  level:
    software.amazonaws.example: WARN
    root: WARN