# Simplified Spring Boot configuration
spring:
  application:
    name: lambda-java-template
  main:
    web-application-type: none
  
logging:
  level:
    root: INFO
    software.amazonaws.example: INFO
    org.springframework: WARN

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true