# Production Native Profile Configuration
# Optimized for Lambda production deployment with minimal cold start

spring:
  main:
    lazy-initialization: false
    web-application-type: none
    banner-mode: "off"
  devtools:
    restart:
      enabled: false

# Production PowerTools configuration
powertools:
  service-name: ${POWERTOOLS_SERVICE_NAME:prod-lambda-service}
  log-level: ${POWERTOOLS_LOG_LEVEL:WARN}
  logger-sample-rate: ${POWERTOOLS_LOGGER_SAMPLE_RATE:0.01}
  logger-log-event: ${POWERTOOLS_LOGGER_LOG_EVENT:false}
  metrics-namespace: ${POWERTOOLS_METRICS_NAMESPACE:ProductionLambda}
  metrics-capture-cold-start: true
  trace-disabled: ${POWERTOOLS_TRACE_DISABLED:false}
  tracer-capture-response: ${POWERTOOLS_TRACER_CAPTURE_RESPONSE:false}
  tracer-capture-error: true

# Minimal production logging
logging:
  level:
    root: WARN
    software.amazonaws.example: INFO
    org.springframework: ERROR
    com.amazonaws: ERROR
    software.amazon.awssdk: ERROR
    io.netty: ERROR

# Production-only actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: never

# Production feature flags
feature-flags:
  debug-mode: false
  detailed-logging: false
  performance-monitoring: false
  cache-enabled: true
  native-optimizations: true
  production-mode: true